<a href="https://colab.research.google.com/github/brownst8-jpg/INFO450/blob/main/INFO450_movie_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🎬 In-Class Python Practice — Movie Night!

**INFO 450 — Summer 2026**

Welcome! Today you'll practice everything we've covered so far, all with a fun **movies** dataset.

**How this works**
- Read each text cell, then fill in the code cell below it where you see `# YOUR CODE HERE`.
- Run each cell with **Shift + Enter**.
- Work through it top to bottom — later cells build on earlier ones.
- Stuck? Ask a neighbor or raise your hand. 🙋

**Time:** ~45 minutes  &nbsp;|&nbsp;  **Topics:** variables, data structures, loops, conditionals, list comprehension, functions, lambda, pandas, APIs, and pushing to GitHub.

Put your name and the date below, then run the cell.

In [1]:
# Run me first!
my_name = "Shayana Brown"
todays_date = "2026-07-01"

print("Notebook by:", my_name)
print("Date:", todays_date)
print("Let's go! 🍿")

Notebook by: Shayana Brown
Date: 2026-07-01
Let's go! 🍿

## 1. Variables  ⏱️ ~3 min

A **variable** is just a labeled box that holds a value. You can hold text (`str`), whole numbers (`int`), decimals (`float`), and True/False (`bool`).

**Your turn:** Create the four variables described in the comments.

In [52]:
# Create these variables about your FAVORITE movie:
# favorite_movie  -> the title, as text (a string)
# release_year    -> the year it came out, a whole number
# my_rating       -> your rating out of 10, a decimal like 8.5
# have_seen_twice -> True or False, have you watched it more than once?

favorite_movie = "Princess and The Frog"
release_year = 2009
my_rating = 10
have_seen_twice = True

# The line below prints them. It will work once you've made the variables above.
print(favorite_movie, "came out in", release_year)
print("My rating:", my_rating, "/ 10")
print("Seen it twice?", have_seen_twice)

Princess and The Frog came out in 2009
My rating: 10 / 10
Seen it twice? True

## 2. Data Structures: Lists & Dictionaries  ⏱️ ~5 min

- A **list** is an ordered collection: `["a", "b", "c"]`
- A **dictionary** stores **key → value** pairs: `{"title": "Inception", "year": 2010}`

Below is our dataset for today: a **list of dictionaries**, where each dictionary is one movie. Run it as-is — don't change it.

In [5]:
movies = [
    {"title": "The Matrix",        "year": 1999, "rating": 8.7, "genre": "Sci-Fi"},
    {"title": "Toy Story",         "year": 1995, "rating": 8.3, "genre": "Animation"},
    {"title": "Parasite",          "year": 2019, "rating": 8.5, "genre": "Thriller"},
    {"title": "Spirited Away",     "year": 2001, "rating": 8.6, "genre": "Animation"},
    {"title": "The Dark Knight",   "year": 2008, "rating": 9.0, "genre": "Action"},
    {"title": "Get Out",           "year": 2017, "rating": 7.7, "genre": "Thriller"},
    {"title": "La La Land",        "year": 2016, "rating": 8.0, "genre": "Musical"},
    {"title": "Interstellar",      "year": 2014, "rating": 8.7, "genre": "Sci-Fi"},
]

print("We have", len(movies), "movies loaded.")
movies[0]  # peek at the first one

We have 8 movies loaded.

{'title': 'The Matrix', 'year': 1999, 'rating': 8.7, 'genre': 'Sci-Fi'}

**Your turn:** Practice pulling values out of the list and dictionaries.

In [53]:
# 1) Print the title of the FIRST movie in the list.
#    Hint: movies[0] is the first dictionary, then use the "title" key.
print(movies[0]["title"])

# 2) Print the rating of the LAST movie in the list.
#    Hint: movies[-1] gives you the last item.
print(movies[-1]["rating"])

The Matrix
8.7

## 3. Loops  ⏱️ ~5 min

A **for loop** repeats an action for every item in a collection.

```python
for movie in movies:
    print(movie["title"])
```

**Your turn:** Loop through `movies` and print one line per movie in the format:
`Parasite (2019) — rating 8.5`

In [11]:
# Loop over every movie and print: "Title (year) — rating X"
# YOUR CODE HERE
for movie in movies:
    print(movie["title"], "(", movie["year"], ") — rating", movie["rating"])

The Matrix ( 1999 ) — rating 8.7
Toy Story ( 1995 ) — rating 8.3
Parasite ( 2019 ) — rating 8.5
Spirited Away ( 2001 ) — rating 8.6
The Dark Knight ( 2008 ) — rating 9.0
Get Out ( 2017 ) — rating 7.7
La La Land ( 2016 ) — rating 8.0
Interstellar ( 2014 ) — rating 8.7

## 4. Conditionals (if / elif / else)  ⏱️ ~5 min

Conditionals let your code make decisions.

```python
if rating >= 9.0:
    print("Masterpiece")
elif rating >= 8.0:
    print("Great")
else:
    print("Good")
```

**Your turn:** Loop through the movies. For each one, print the title and a label:
- rating **9.0 or higher** → `"Masterpiece"`
- rating **8.0 to 8.9** → `"Great"`
- anything lower → `"Good"`

In [24]:
# Loop through movies and print each title with its label.
# YOUR CODE HERE
for movie in movies:
    rating = movie["rating"]
    if rating >= 9.0:
        print(movie["title"], "Masterpiece")
    elif rating >= 8.0:
        print(movie["title"], "Great")
    else:
        print(movie["title"], "Good")

The Matrix Great
Toy Story Great
Parasite Great
Spirited Away Great
The Dark Knight Masterpiece
Get Out Good
La La Land Great
Interstellar Great

## 5. List Comprehension  ⏱️ ~5 min

A **list comprehension** builds a new list in one compact line.

```python
titles = [movie["title"] for movie in movies]
```

You can also **filter** with an `if` at the end:

```python
recent = [m["title"] for m in movies if m["year"] >= 2015]
```

**Your turn:** Complete the three comprehensions below.

In [33]:
# 1) A list of ALL genres (may include duplicates).
all_genres = titles = [movie["title"] for movie in movies]
print("Genres:", all_genres)

# 2) A list of titles for movies rated 8.5 or higher.
top_titles = titles = [movie["title"] for movie in movies if rating >= 8.5]
print("Top rated:", top_titles)

# 3) A list of titles from movies made in the year 2000 or LATER.
this_century = recent = [movie["title"] for movie in movies if movie["year"] >= 2000]
print("2000 and later:", this_century)

Genres: ['The Matrix', 'Toy Story', 'Parasite', 'Spirited Away', 'The Dark Knight', 'Get Out', 'La La Land', 'Interstellar']
Top rated: ['The Matrix', 'Toy Story', 'Parasite', 'Spirited Away', 'The Dark Knight', 'Get Out', 'La La Land', 'Interstellar']
2000 and later: ['Parasite', 'Spirited Away', 'The Dark Knight', 'Get Out', 'La La Land', 'Interstellar']

## 6. Functions  ⏱️ ~6 min

A **function** is reusable code you can call with different inputs. Define it with `def`, and `return` a result.

```python
def double(x):
    return x * 2
```

**Your turn:** Finish the function so it returns a nice description string for a movie dictionary.

In [35]:
def describe_movie(movie):
    # Should return a string like:
    # "The Matrix is a Sci-Fi film from 1999 rated 8.7"
    # Use the movie's "title", "genre", "year", and "rating" keys.
    return f"{movie['title']} is a {movie['genre']} film from {movie['year']} rated {movie['rating']}"
    pass


# Test it (this should print a full sentence, not "None"):
print(describe_movie(movies[0]))
print(describe_movie(movies[2]))

The Matrix is a Sci-Fi film from 1999 rated 8.7
Parasite is a Thriller film from 2019 rated 8.5

**Your turn (part 2):** Write a function `average_rating` that takes the `movies` list and returns the average of all their ratings.

In [37]:
def average_rating(movie_list):
    # Add up every movie's rating, then divide by how many there are.
    # Hint: len(movie_list) tells you how many movies there are.
    total = 0
    for movie in movie_list:
        total += movie["rating"]
    return total / len(movie_list)
    pass


print("Average rating:", average_rating(movies))

Average rating: 8.4375

## 7. Lambda Functions  ⏱️ ~4 min

A **lambda** is a tiny one-line function with no name. These two are equivalent:

```python
def add_one(x): return x + 1
add_one = lambda x: x + 1
```

Lambdas are handy for **sorting**. `sorted()` takes a `key=` telling it what to sort by.

**Your turn:** Sort the movies by rating, highest first.

In [41]:
# Sort movies by rating, HIGHEST first (descending).
# Fill in the lambda so it returns each movie's rating.
movies_by_rating = sorted(movies, key=lambda m: m["rating"], reverse=True)

for m in movies_by_rating:
    print(m["rating"], m["title"])

9.0 The Dark Knight
8.7 The Matrix
8.7 Interstellar
8.6 Spirited Away
8.5 Parasite
8.3 Toy Story
8.0 La La Land
7.7 Get Out

## 8. Intro to pandas  ⏱️ ~5 min

**pandas** turns data into a table (a **DataFrame**) that's easy to explore. Our list of dictionaries converts to a table in one line. Run the cell below.

In [42]:
import pandas as pd

df = pd.DataFrame(movies)
df

             title  year  rating      genre
0       The Matrix  1999     8.7     Sci-Fi
1        Toy Story  1995     8.3  Animation
2         Parasite  2019     8.5   Thriller
3    Spirited Away  2001     8.6  Animation
4  The Dark Knight  2008     9.0     Action
5          Get Out  2017     7.7   Thriller
6       La La Land  2016     8.0    Musical
7     Interstellar  2014     8.7     Sci-Fi

A few super-simple pandas moves. **Your turn:** fill in the blanks.

In [45]:
# 1) Show just the "title" and "rating" columns.
#    Hint: df[["title", "rating"]]
df[["title", "rating"]]


# 2) The average rating of the whole column, the easy way:
print("Mean rating:", df["rating"].mean())

# 3) Only the rows where genre is "Animation".
#    Hint: df[df["genre"] == "Animation"]
df[df["genre"] == "Animation"]

Mean rating: 8.4375

           title  year  rating      genre
1      Toy Story  1995     8.3  Animation
3  Spirited Away  2001     8.6  Animation

## 9. Working with API Data  ⏱️ ~5 min

When you call an **API**, it usually sends back **JSON**, which in Python looks just like a **dictionary** (and lists of dictionaries) — exactly what you've been practicing!

Normally you'd fetch this live with `requests.get(...)`. To keep us offline today, here's a sample of what a movie API might return. Run it as-is.

In [47]:
# This is a pretend API response (already parsed into a Python dictionary).
api_response = {
    "status": "ok",
    "results": [
        {"name": "Dune: Part Two", "year": 2024, "score": 8.5},
        {"name": "Everything Everywhere All at Once", "year": 2022, "score": 7.8},
        {"name": "Oppenheimer", "year": 2023, "score": 8.3},
    ],
}

print("Status:", api_response["status"])
print("Number of results:", len(api_response["results"]))

Status: ok
Number of results: 3

**Your turn:** The list of movies lives under the `"results"` key.

In [50]:
# 1) Print the "name" of every movie in the API results (use a loop).
print("Movies:")
for movie in api_response["results"]:
    print(movie["name"])


# 2) Turn the API results into a pandas DataFrame and display it.
#    Hint: pd.DataFrame(api_response["results"])
api_df = pd.DataFrame(api_response["results"])
api_df

Movies:
Dune: Part Two
Everything Everywhere All at Once
Oppenheimer

                                name  year  score
0                     Dune: Part Two  2024    8.5
1  Everything Everywhere All at Once  2022    7.8
2                        Oppenheimer  2023    8.3

## 10. Save Your Data & Push to GitHub  ⏱️ ~2 min

Let's save our table to a CSV file — this is the kind of file you'd commit to GitHub.

In [54]:
# Save the movies table to a CSV file (no extra index column).
df.to_csv("movies.csv", index=False)
print("Saved movies.csv ✅  (look in the file browser on the left)")

Saved movies.csv ✅  (look in the file browser on the left)

## 🎉 Done!

You just used **variables, lists, dictionaries, loops, conditionals, list comprehensions, functions, lambdas, pandas, API-style JSON, and saving data for GitHub** — all in one notebook. Nice work!

**Stretch goals if you finish early:**
1. Add 2 more movies to the `movies` list, then re-run the pandas cells.
2. Write a function `movies_in_genre(movie_list, genre)` that returns the titles in a given genre.
3. Sort the API results by `score` using a lambda.

Save your notebook (**File → Save**) before you leave.